# Generated by Django 2.2 on 2019-12-14 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Аватар')),
                ('subscription', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Подпесь')),
                ('date_ct', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created', models.ForeignKey(default=webapp.models.get_admin, on_delete=django.db.models.deletion.PROTECT, related_name='img_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Тецт')),
                ('date_ct', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(default=webapp.models.get_admin, on_delete=django.db.models.deletion.PROTECT, related_name='img_comment', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='img_comment', to='webapp.Photo', verbose_name='Фото')),
            ],
        ),
    ]
