# Generated by Django 2.2 on 2019-12-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191214_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='subscription',
            field=models.TextField(max_length=3000, verbose_name='Подпесь'),
        ),
    ]
